# Generated by Django 5.1.4 on 2024-12-14 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='nft',
            name='collection',
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Художник', 'verbose_name_plural': 'Художники'},
        ),
        migrations.AlterModelOptions(
            name='artistimage',
            options={'verbose_name': 'Аватвар', 'verbose_name_plural': 'Аватар'},
        ),
        migrations.AlterModelOptions(
            name='nft',
            options={'verbose_name': 'NFT', 'verbose_name_plural': 'NFT'},
        ),
        migrations.AlterModelOptions(
            name='nftcategory',
            options={'verbose_name': 'NFT категории', 'verbose_name_plural': 'NFT категории'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиль'},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='nftcategory',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='nftcategory',
            name='price_range',
        ),
        migrations.AddField(
            model_name='nft',
            name='minted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='change_percentage',
            field=models.FloatField(verbose_name='Изменение'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nfts_sold',
            field=models.PositiveIntegerField(verbose_name='Количество проданных NFT'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объем продаж в ETH'),
        ),
        migrations.AlterField(
            model_name='artistimage',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='account.artist', verbose_name='фото худ'),
        ),
        migrations.AlterField(
            model_name='artistimage',
            name='image',
            field=models.ImageField(upload_to='artist_images/', verbose_name='изображ'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfts', to='account.artist', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высшая ставка'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Изображения NFT'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='nftcategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='account.artist', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='nftcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Нахвание Категории'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='account.artist', verbose_name='профиль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография '),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='discord',
            field=models.URLField(blank=True, null=True, verbose_name='Discord'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.PositiveIntegerField(verbose_name='Количество подписчиков'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nfts_sold',
            field=models.PositiveIntegerField(verbose_name='Количество проданных NFT'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объем продаж'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(max_length=255, verbose_name='Кошельек'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='описание')),
                ('blockchain', models.CharField(default='Ethereum', max_length=255, verbose_name='Блокчейн')),
                ('etherscan_link', models.URLField(blank=True, null=True, verbose_name='Etherscan')),
                ('original_link', models.URLField(blank=True, null=True, verbose_name='оригинальная ссылка')),
                ('nft', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to='account.nft', verbose_name='Для какой nft')),
                ('tags', models.ManyToManyField(related_name='collections', to='account.tag', verbose_name='тэг')),
            ],
            options={
                'verbose_name': 'Детальная информация',
                'verbose_name_plural': 'Детальная информация',
            },
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
